### ISSUE TITLE
The map displayed in the Weather page is incorrect

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-flutter-app#1]
Please set the location to Panamá
![IMG_2095](https://user-images.githubusercontent.com/46169036/95771697-1c4c2980-0c81-11eb-9af8-9a5a6a1f0372.PNG)

**Comment by godslave05** [comment]
Build to test: 0.0.7+9

**Comment by Ray-LZ** [comment]
Hi @godslave05 could you please check why it's opening differently in iOS & Android devices?
iOS
![image](https://user-images.githubusercontent.com/46169036/99557837-b9893480-2988-11eb-84f9-66e8f6586db4.png)
Android (expected result)
![image](https://user-images.githubusercontent.com/46169036/99557915-cd349b00-2988-11eb-8940-aab13e73c8d8.png)

**Comment by godslave05** [comment]
@Ray-LZ I have increased zoom level from 5 to 7.
You can see the result in 0.0.7+10

**Comment by godslave05** [comment]
![screenshot-2021-02-04_19 35 17 468](https://user-images.githubusercontent.com/13714742/106899927-23131680-6720-11eb-9c62-dce121d21f7f.png)
@Ray-LZ this is how it looks in android now.
@diegopau can close this issue
