### ISSUE TITLE
Not able to create emergency contact on iOS

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#101]
Please check in a new account I was not able to provide my emergency contact 
Notes: 
Android test passed
iOS worked fine only for editing the emergency contact
Please edit the text on the error message

**Comment by diegopau** [comment]
Ray Zaragoza
July 4, 2020, 12:32 AM

Able to reproduce tested on iPad app version 0.7+3
![image-20200703-223217](https://user-images.githubusercontent.com/315149/97470604-0066aa00-1948-11eb-8a8c-b7e0e6101fa9.png)

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
