### ISSUE TITLE
Screen incorrectly displayed on iPad 9.7"

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#102]
![image-2020-05-14-19-18-04-143](https://user-images.githubusercontent.com/315149/97470746-30ae4880-1948-11eb-9a59-2e1b53f45b70.png)

**Comment by Ray-LZ** [comment]
Test passed 0.0.7(8)
![image](https://user-images.githubusercontent.com/46169036/97506424-8252d500-1940-11eb-8448-1be1157891e5.png)
