### ISSUE TITLE
Unify Request Access with Grant Access roles

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#103]
Grant Access: Member & Guest
![image-20200601-144547](https://user-images.githubusercontent.com/315149/97470935-70753000-1948-11eb-9293-03f06b34abb2.png)

Request Access: Visitor, Guest & Member
![image-20200601-144714](https://user-images.githubusercontent.com/315149/97470952-74a14d80-1948-11eb-872e-9f7d77a0a5cf.png)

**Comment by diegopau** [comment]
Ray Zaragoza
June 29, 2020, 10:01 PM

Hi Abdullah Asad “visitor” access has to be added to Grant Access As (access type)

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
