### ISSUE TITLE
Access Request Screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#104]
iPad 9.7" screen >> looks too big
![image-20200606-191208](https://user-images.githubusercontent.com/315149/97471034-96023980-1948-11eb-9a8d-95b2d3c9704e.png)

this is how it looks on 5.7”
![image-20200606-191304](https://user-images.githubusercontent.com/315149/97471087-a31f2880-1948-11eb-8fee-f5809a0b12e9.png)

**Comment by diegopau** [comment]
Ray Zaragoza
August 8, 2020, 1:02 AM

Abdullah Asad please add deny and accept buttons

**Comment by godslave05** [comment]
fixed
