### ISSUE TITLE
Intergrate API in View Permission Screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#106]
API Integration
Get Permission by ID

Manage Permissions --> View Permission Details

**Comment by Ray-LZ** [comment]
Please check this @godslave05 when I tap the manage permission button a gray layer is displayed
![image](https://user-images.githubusercontent.com/46169036/98747613-783bc800-237d-11eb-85e1-2556f1258e91.png)

**Comment by godslave05** [comment]
fixed
