### ISSUE TITLE
Not able to close a popup

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#113]
Tapping the :cross_mark: or the cancel button, doesn't close this popup 

![image-20200702-210558](https://user-images.githubusercontent.com/315149/97573218-b504d800-19e9-11eb-9318-47045d25fddc.png)

**Comment by diegopau** [comment]
Ray Zaragoza
July 2, 2020, 11:16 PM

The same happened with this one
![Screenshot_20200702-161451](https://user-images.githubusercontent.com/315149/97573254-bfbf6d00-19e9-11eb-96ee-ce1c6284fd7d.png)

**Comment by diegopau** [comment]
When the user tap uv radiation
![IMG_1520](https://user-images.githubusercontent.com/315149/97573296-cea61f80-19e9-11eb-851e-6f7ca27a06c8.png)

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
