### ISSUE TITLE
Access management screen is not displaying all the users that have access to a seapod

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#117]
I have accepted an access request 
![image-20200702-220145](https://user-images.githubusercontent.com/315149/97573668-6dcb1700-19ea-11eb-88c9-d5813386a61b.png)
However it is not displayed under Access Management screen 
![image-20200702-220431](https://user-images.githubusercontent.com/315149/97573705-7a4f6f80-19ea-11eb-97ef-afecda3bfabd.png)

**Comment by diegopau** [comment]
Abdullah Asad
July 5, 2020, 12:28 PM

Please check 0.0.7+4

**Comment by Ray-LZ** [comment]
test passed app version 0.7.0(8)
