### ISSUE TITLE
Set default access duration for request access type other than Guest type

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#121]

**Comment by Ray-LZ** [comment]
Member
![image](https://user-images.githubusercontent.com/46169036/99831851-57196b00-2b25-11eb-96b3-3de06002446c.png)

Visitor
![image](https://user-images.githubusercontent.com/46169036/99831907-68627780-2b25-11eb-8a0f-cf2d6391d999.png) 

Guest
![image](https://user-images.githubusercontent.com/46169036/99831963-7adcb100-2b25-11eb-930d-52885c0ed17d.png)
