### ISSUE TITLE
Process access request and access invitation list to show different access event list in access management screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#122]
Process login response from server to fill the following list in access management screen
Sent invitations
Sent requests
received requests
received invitations

**Comment by Ray-LZ** [comment]
Implemented app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/98745140-9b17ad80-2378-11eb-9e38-632aed7ff593.png)
