### ISSUE TITLE
Communicate with IOT server of Smart Home using MQTT protocol

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#137]
Smart Home (MQTT) screen

**Comment by godslave05** [comment]
Build to test: 0.0.7+9

**Comment by Ray-LZ** [comment]
Implemented app version 0.7.0(9)
![image](https://user-images.githubusercontent.com/46169036/99561489-a11b1900-298c-11eb-9a69-948550cd3dc6.png)
