### ISSUE TITLE
Add formula for missing weather attributes

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#138]
Add formula for feels like temperature

**Comment by godslave05** [comment]
Build to test: 0.0.7+9 0r 0.0.7+8

**Comment by Ray-LZ** [comment]
Implemented, app version 0.7.0(9)
![image](https://user-images.githubusercontent.com/46169036/99555550-0e777b80-2986-11eb-9292-b9e4dbd3f2a8.png)
