### ISSUE TITLE
Communicate with Smart Home node js server

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#139]
This task is reflected on the Smart Home(Node server) Screen

**Comment by godslave05** [comment]
Build to test: 0.0.7+9

**Comment by Ray-LZ** [comment]
Implemented, app version 0.7.0(9)
![image](https://user-images.githubusercontent.com/46169036/99556948-c0637780-2987-11eb-9671-c6c3d5131789.png)
