### ISSUE TITLE
Integrate ON/OFF API for lights of lighting scene 

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#140]

**Comment by diegopau** [comment]
Ray Zaragoza
October 12, 2020, 5:57 PM

Hi Abdullah Asad when I first test this there was an error message displayed related to wrong light scene id, after that, this error message is displayed
Tested on 0.0.7(8)

![Uploading Screenshot_20201012-105414.png…]()

**Comment by godslave05** [comment]
Build to test: 0.0.7+9

**Comment by Ray-LZ** [comment]
test passed 0.0.7+9
