### ISSUE TITLE
Upgrade graph related library package code to work with the latest flutter version and plugins

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#141]
All the graph should work without any issue in the latest build

**Comment by Ray-LZ** [comment]
The graphs look like expected, app version 0.7.0(9)
![image](https://user-images.githubusercontent.com/46169036/99560134-256c9c80-298b-11eb-8f44-e5d7e3ca439e.png)

![image](https://user-images.githubusercontent.com/46169036/99560185-35847c00-298b-11eb-922e-c9144da281d1.png)
