### ISSUE TITLE
Toogle Light Status failed

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-flutter-app#143]
Steps to Reproduce:
Turn off and on the button shown in the screenshot
![image](https://user-images.githubusercontent.com/46169036/97612069-8fbd9d00-19dc-11eb-8846-70236a4d52f7.png)

**Comment by godslave05** [comment]
It's working in 0.7+9, could you check again in 0.7+9
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-14 at 22 59 13](https://user-images.githubusercontent.com/13714742/99152925-36898500-26cf-11eb-9371-a32a6c0dae23.png)

**Comment by Ray-LZ** [comment]
Hi @godslave05 it seems that a lighting scene "can get damaged" on the video you will see how toogle light status will work with 1 seapod but it will fail when I switched to a different seapod
ray@scissorboy.com | Changeme333$ 
https://drive.google.com/file/d/1JhdUA-LDz472D4RqyM6scW1tQsnylNVX/view?usp=sharing 

Weird thing is, if you check   access management page "Ray Main Account"  (ray@scissorboy.com) is not displed in both seapods

**Comment by Ray-LZ** [comment]
Closing this, duplicated of #129
