### ISSUE TITLE
Design: We should find a way to improve "Access Management" screen

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-flutter-app#145]
Hi @Bruno-N Below some suggestions app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/98745750-bb943780-2379-11eb-9b0d-1388dc9407f1.png)

Design v0.7 
![image](https://user-images.githubusercontent.com/46169036/98745981-39f0d980-237a-11eb-8a46-f6c0f8083a8d.png)

I'm not sure if we should take care of the design of this screen or it will drastically change in future versions

**Comment by scottdear** [comment]
Closing this issue as it appears it is no longer moving forward?
