### ISSUE TITLE
Create Email template

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-flutter-app#31]

**Comment by Mikisson** [comment]
**Abdullah Asad** _January 25, 2020, 1:43 PM_
Possible email in the app:

1. Email for account verification
2. Email to get access request
3. Email to get access invitation
4. Email to get urgent notification

**Comment by Mikisson** [comment]
**Abdullah Asad** _January 28, 2020, 5:03 AM_

Cristina Bogdan; Diego Ocampo;
Email for account verification Text:
I think this texts may change depending on the design you choose. The text could be like this
You're almost ready to go.
Click this button to verify your email address and finish setting up your account.<button> CONFIRM YOUR EMAIL ADDRESS </button>
<button> NOT YOU? </button>

Cheers!
The Ocean Builders Team

Email to get access request:

RAY has requested access to your seapod RED MARITIME ( OB2XNaK ) for permanent access starting on January 11, 2020.

Ray is awaiting your response. Please open the Oceanbuilder app and respond to this request.

Email to get access invitation:
DIEGO has invited you to access seapod DARK DREAMER ( OB21ujH ) for 15 days starting on January 6, 2020.

DIEGO is awaiting your response. Please open the Oceanbuilder app and respond to this invitation.

Email to get urgent notification:
I am not sure about this

**Comment by Mikisson** [comment]
**Diego Ocampo** _January 31, 2020, 8:00 AM_
Email to get urgent notifications

Subject: IMPORTANT action needed on your SeaPod

Hi {Name},

Your SeaPod {seapod_name} is currently having the following issue {urgent_event_description}

Please remember that you can contact us any time at {contact_phone} or {contact_email}

Make sure you have notifications enabled on the Ocean Builders app if you want to be aware of any urgent issues.

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 3, 2020, 5:10 PM_

Hi Abdullah Asad I am not receiving emails yet. Is this ready to be tested?

**Comment by Mikisson** [comment]
**Abdullah Asad** _July 3, 2020, 11:23 PM_

This task was for creating the template mails.
Mails will be sent from server. May be in 0.8

**Comment by Mikisson** [comment]
**Ray Zaragoza** _July 13, 2020, 11:37 AM_

Pending to test until the functionality for receiving emails is not ready.
The template is done 

- The email template will have a link that will redirect directly to the app

**Comment by Ray-LZ** [comment]
@godslave05 I'm closing this card since you mentioned the email template has been created, please create a card for testing this when the app is ready
