### ISSUE TITLE
iPhone 11 screens

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-flutter-app#39]
![image-2020-02-03-18-49-07-579](https://user-images.githubusercontent.com/72101387/96732641-dac22980-13b8-11eb-8a22-2345c11300a1.png)

**Comment by Mikisson** [comment]
**Abdullah Asad** _February 4, 2020, 12:49 AM_
What is the issue ?

**Comment by Mikisson** [comment]
**Ray Zaragoza** _February 4, 2020, 10:42 AM_
The spacing between Steering widget and bottom clipper

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97506989-d90cde80-1941-11eb-9938-45a972ce6fbe.png)
