### ISSUE TITLE
Integrating 3D models on our app

### ISSUE THREAD

**Issue by Mikisson** [oceanbuilders/ob-flutter-app#4]
Here is an interesting feature we want to add to our demo app, and quite high priority so we can ask the designers to start this ASAP.

We plan to integrate 3D models of the OBs in our app. We need to find out what is the best format to make this work no our Fluttler app, then we will ask the designers to deliver in that specific format. Obviously much better if the format chosen is a standard that is widely used, so it will make things easier for the designer.

To give you an idea of the kind of 3D model we plan to integrate here is an example: https://assetstore.unity.com/packages/3d/characters/humanoids/male-scuba-diver-pro-43772 (please click here https://www.dropbox.com/s/bao005dd4lk5j5b/Screenshot%202019-07-19%2013.24.04.png?dl=0)

It has to work on iOS, Android and also web app!

EDIT: please keep in mind, we might want to do more cool things with this like:

- allowing rotating, pinch and zoom, etc
- allowing to tap on a specific part of the model, highlight it, and show data for that specific part: we want to be able to select a  room of the OB using the 3D model, then see/control sensors of that room.
- Rotate and zoom to a specific part of the 3D model: we might want the app to automatically rotate the model and zoom in and highlight a specific part
- change colors / textures in real time of specific parts of the model
- Add / remove portions of the 3D model.

**Comment by Mikisson** [comment]
**Abdullah- Al- Asad (Godslave)** _July 19, 2019, 1:56 PM_
This is reminding me my Game development career on LIbgdx and Unity 3D.  With any one of those this would be fun to do. 
But with Flutter ! WelI I need to do some research first. :-)

**Comment by Mikisson** [comment]
**Diego Ocampo** _July 19, 2019, 3:55 PM_
Abdullah- Al- Asad (Godslave) yeah i imagine we are very limited, I want to think this is possible because Grant is already dreaming about this possibility, it would be a big win if we manage to do this kind of thing. Take your time, we will discuss on Monday

**Comment by godslave05** [comment]
prototype implemented
