### ISSUE TITLE
Notification Settings Screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#78]
![IMG_1287](https://user-images.githubusercontent.com/315149/97034679-91fba380-1565-11eb-99f5-adcf567da836.png)

**Comment by ray-scissorboy** [comment]
test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97372433-3d17a000-1879-11eb-8097-9e1119111bf3.png)
