### ISSUE TITLE
Add seapod management and subitems in navigation drawer

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#80]
![image-20200605-215657](https://user-images.githubusercontent.com/315149/97035102-249c4280-1566-11eb-8e7c-18a11af5a33d.png)

**Comment by diegopau** [comment]
Ray Zaragoza
May 28, 2020, 8:09 PM

please elaborate Abdullah Asad

**Comment by diegopau** [comment]
Abdullah Asad
May 29, 2020, 3:21 PM

Design Implementation
Add submenu under SeaPod Management  in the Navigation Drawer List Menu
Ref: https://www.figma.com/file/Oum9Yn15E0GTEGPjt5Jho9/OB-0.7?node-id=0%3A1

**Comment by diegopau** [comment]
Please rename to “SEAPOD MANAGEMENT”
The text should be all aligned
![Uploading image-20200605-215657 (1).png…]()

**Comment by ray-scissorboy** [comment]
test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97372307-f7f36e00-1878-11eb-9c7c-689ef4acfba4.png)
