### ISSUE TITLE
Add changes to access management screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#83]
![image-20200605-221935](https://user-images.githubusercontent.com/315149/97035541-c7ed5780-1566-11eb-9f39-2f298f9f2698.png)
![image-20200605-223053](https://user-images.githubusercontent.com/315149/97035542-c885ee00-1566-11eb-8d9f-b973f95c0796.png)

**Comment by diegopau** [comment]
Abdullah Asad
May 29, 2020, 3:34 PM
Edited

Design Implementation
Added Access event types 
Sent Invitation
Received Invitation
Sent Request
Received Request
Request access button  , Grant Access Button
Ref: https://www.figma.com/file/Oum9Yn15E0GTEGPjt5Jho9/OB-0.7?node-id=0%3A1

**Comment by diegopau** [comment]
Ray Zaragoza
June 6, 2020, 12:30 AM
Edited

Please make rounded corners and add space between the title and sent invitations
![image-20200605-223053 (1)](https://user-images.githubusercontent.com/315149/97035616-e3586280-1566-11eb-9c97-ee9fa6e0a632.png)
![image-20200605-221935 (1)](https://user-images.githubusercontent.com/315149/97035619-e3f0f900-1566-11eb-98ed-4a6e669e5d3e.png)

**Comment by diegopau** [comment]
Ray Zaragoza
June 29, 2020, 7:00 PM
Edited

Administration and Owner the first letter should be a capital letter.
Need new build to check “Remove” the accepted users are not displayed under Access Management

**Comment by ray-scissorboy** [comment]
test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97372189-a519b680-1878-11eb-834b-65ea98b0057b.png)
![image](https://user-images.githubusercontent.com/46169036/97372203-afd44b80-1878-11eb-8b05-b600714f92ac.png)
