### ISSUE TITLE
administration access screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#85]
Design Implementation

Guest Access Screen
Route
Access Management Screen → Administrator User → Administrator Access Screen
![image-20200606-183125](https://user-images.githubusercontent.com/315149/97035813-2d414880-1567-11eb-8f51-05585a0c58b3.png)

**Comment by ray-scissorboy** [comment]
test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97372021-389eb780-1878-11eb-8f57-57621f5757c0.png)
