### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#94]
To organize and update some of the classes to use updated flutter features
tasks pertaining to the changes of library and packages which are touched by the flutter upgrade

**Comment by diegopau** [comment]
@godslave05 please add the estimate off all this work with a bit of detail. This has been a big project so we should specify what changes you did and how long it took you each

**Comment by godslave05** [comment]
refactored code structure and upgraded to use the latest libraries
estimated time 20 hours
