### ISSUE TITLE
the images look pixelated (left side menu)

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#95]
![pixelated](https://user-images.githubusercontent.com/315149/97178075-4af4f480-1797-11eb-8a0f-6550f91d234e.PNG)
 it is easy to note the pixelation with the key image under “access management”

**Comment by diegopau** [comment]
Ray Zaragoza
August 8, 2020, 12:52 AM

Hi Abdullah Asad please check this

![IMG_1758](https://user-images.githubusercontent.com/315149/97178136-5ea05b00-1797-11eb-80e0-d8edcb294307.png)

**Comment by ray-scissorboy** [comment]
test passed 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97362178-3895bc00-1866-11eb-87fb-b8c98226b6ba.png)
