### ISSUE TITLE
Remove save design related design changes 

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#96]

**Comment by diegopau** [comment]
Ray Zaragoza
July 4, 2020, 12:21 AM

Abdullah Asad please elaborate

**Comment by diegopau** [comment]
Abdullah Asad
July 4, 2020, 6:29 AM

Ray Zaragoza 
You should not see any thing related to save design option in the app now.
This functionality is deprecated now.

**Comment by Ray-LZ** [comment]
Test passed we don't see anything related to save design while creating an account
App version 0.7.0(8)
