### ISSUE TITLE
The wrong label is displayed

### ISSUE THREAD

**Issue by Ray-LZ** [oceanbuilders/ob-flutter-app#97]
Tested with app version 0.7.0(8)
Actual Result: In the "select a home" page the user ray@scissorboy.com | Changeme333$ is a "guest" of the seapod RedSummer, however, the label owner is displayed.

Expected Result: "guest" label is displayed 
![image](https://user-images.githubusercontent.com/46169036/97366711-603c5280-186d-11eb-8aee-f882c3348522.png)

**Comment by godslave05** [comment]
fixed in last version
