### ISSUE TITLE
Add request Access screen

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-flutter-app#99]
From Access Management screen there is an option to Request access for new seapod.
That should work

**Comment by diegopau** [comment]
Ray Zaragoza
July 2, 2020, 11:53 PM
Edited

The Request Access button has been added to Access Management screen.
Abdullah Asad pls check why the “Next” button is not clickable and how the text is displayed when the user selects “Member”


![image-20200702-215325](https://user-images.githubusercontent.com/315149/97470244-9cdc7c80-1947-11eb-99b8-6226a64b1e2e.png)

**Comment by Ray-LZ** [comment]
Test passed app version 0.7.0(8)
![image](https://user-images.githubusercontent.com/46169036/97642963-189ffd00-1a0c-11eb-8170-c87498025c9c.png)
